version: '3.1'

services:

  proxy:
    build: ./reverse-proxy
    container_name: proxy
    image: yuttasakcom/yoprogrammer-proxy:1.0.0
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

  web:
    build: .
    container_name: web
    image: yuttasakcom/yoprogrammer-web:1.0.0
    environment:
      - NODE_ENV=production
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
