version: '3.1'

services:

  proxy:
    build: ./nginx
    image: yuttasakcom/yoprogrammer-nginx:1.0.0
    container_name: proxy
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

  web:
    build: .
    container_name: web
    image: yuttasakcom/yoprogrammer-web:1.0.0
    environment:
      - NODE_ENV=production
      - HOST=yoprogrammer.com
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: overlay
